live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.cursor]
cursor = "0xcecacd"
text = "0x575279"

[colors.normal]
black = "0x393552"
blue = "0x9ccfd8"
cyan = "0xea9a97"
green = "0x3e8fb0"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x232136"
foreground = "0xe0def4"

[font]
size = 11

[font.bold]
family = "JetBrains Mono Medium"
style = "regular"

[font.bold_italic]
family = "JetBrains Mono Medium"
style = "regular"

[font.italic]
family = "JetBrains Mono Medium"
style = "regular"

[font.normal]
family = "JetBrains Mono Medium"
style = "egular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[window]
dynamic_padding = true

[window.padding]
x = 10
y = 5
