#!/bin/bash

oldImg=$(cat ~/.config/waybar/temp)

list[0]=wallpaper1.jpg
list[1]=wallpaper2.jpg
list[2]=wallpaper3.jpg
list[3]=wallpaper4.jpg
list[4]=wallpaper5.jpg
list[5]=wallpaper.png
list[6]=wallpaper6.jpg
list[7]=wallpaper7.jpg

size=${#list[@]}
index=$((RANDOM % $size))
img=${list[$index]}

while [[ $img = $oldImg ]] ; do
	 index=$((RANDOM % $size))
	 img=${list[$index]}
done

echo $img > ~/.config/waybar/temp

swww img ~/.config/waybar/wallpapers/$img --transition-type grow --transition-pos 1460,1375 --transition-duration 3
