#!/usr/bin/bash

color="#f7dab6"

function get_brightness {
  xbacklight -get
}

function send_notification {
  brightness=$(get_brightness)
	brightness_icon="󰃠"
  dunstify -u normal "$brightness_icon ${brightness}%" -r 5555 -h int:value:"$brightness" -h string:hlcolor:$color
}

case $1 in
  up)
    xbacklight -inc 10
    send_notification
    ;;
  down)
    xbacklight -dec 10
    send_notification
    ;;
esac
