#!/usr/bin/bash

swaylock \
--image "$HOME/Downloads/123.jpg" \
--font "JetBrainsMono Nerd Font" \
--font-size 40 \
--indicator \
--indicator-x-position 120 \
--indicator-y-position 600 \
--clock \
--datestr "%a %d/%m/%y" \
--show-keyboard-layout \
--inside-wrong-color f38ba8  \
--ring-wrong-color 11111b  \
--inside-clear-color a6e3a1 \
--ring-clear-color 11111b \
--inside-ver-color 89b4fa \
--ring-ver-color 11111b \
--text-color f7768e \
--indicator-radius 60 \
--indicator-thickness 5 \
--effect-blur 2x2 \
--effect-vignette 0.3:0.3 \
--ring-color 11111b \
--key-hl-color f5c2e7 \
--line-color 313244 \
--inside-color 0011111b \
--separator-color 00000000 \
